# GitHub Labels Configuration
# To sync: gh label sync -f .github/labels.yml

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "ci-failure"
  color: "b60205"
  description: "CI/CD pipeline failure"

- name: "claude-task"
  color: "7057ff"
  description: "Task for Claude Code to handle"

- name: "automated"
  color: "ededed"
  description: "Automatically created issue"

- name: "needs-triage"
  color: "fbca04"
  description: "Needs initial assessment"

- name: "good-first-issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help-wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "priority-high"
  color: "d93f0b"
  description: "High priority"

- name: "priority-medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority-low"
  color: "0e8a16"
  description: "Low priority"

- name: "security"
  color: "b60205"
  description: "Security-related issue"

- name: "testing"
  color: "1d76db"
  description: "Related to testing"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
