name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your ideas help make HA Boss better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What limitation are you experiencing?
      placeholder: |
        Currently, I cannot...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Be as detailed as possible.
      placeholder: |
        The feature should:
        1. Allow users to...
        2. When X happens, Y should...
        3. The output would be...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Monitoring (WebSocket, health checks, state tracking)
        - Healing (integration reload, strategies, cooldowns)
        - AI/Intelligence (LLM integration, analysis, insights)
        - Automation (generation, analysis, optimization)
        - Pattern Analysis (reliability, failure tracking, metrics)
        - CLI (new commands, output formats)
        - Configuration (new options, validation)
        - Notifications (new channels, templates)
        - Database (schema, queries, storage)
        - API (REST endpoints, WebSocket)
        - Docker/Deployment
        - Documentation
        - Multiple components
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use case
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I have 50+ integrations and need to...
        My smart home setup involves...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        I tried using...
        Currently I work around this by...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, examples, or related features
      placeholder: |
        Similar to how [other tool] does...
        Example configuration:
        ```yaml
        new_feature:
          enabled: true
          option: value
        ```

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in contributing?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I can help test this feature

  - type: checkboxes
    id: claude-assignable
    attributes:
      label: Claude Assignment
      description: Should this be assigned to Claude for implementation?
      options:
        - label: Assign to Claude (@claude)
